require:
- rubocop-rake
- rubocop-rspec
- rubocop-rails
- rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
  - 'bin/**/*'
  - 'spec/dummy/bin/**/*'
  - 'rspec-documentation/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 8

Metrics/ParameterLists:
  Exclude:
  - 'lib/active_element/components/**/*.rb'
  - 'lib/active_element/active_element_component.rb'
