require:
- rubocop-rake
- rubocop-rspec
- rubocop-rails
- rubocop-factory_bot
- rubocop-rspec-documentation

AllCops:
  NewCops: enable
  Exclude:
  - 'bin/**/*'
  - 'rspec-documentation/dummy/**/*'
  - 'example_app/**/*'
  - 'spec/dummy/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 8

Metrics/ParameterLists:
  Exclude:
  - 'lib/active_element/components/**/*.rb'
  - 'lib/active_element/active_element_component.rb'

Style/SymbolArray:
  Exclude:
  - 'rspec-documentation/pages/**/*.md'

Style/Style/WordArray:
  Exclude:
  - 'rspec-documentation/pages/**/*.md'
